<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Interfaces\Repositories\" />
    <Folder Include="Services\" />
    <Folder Include="Records\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InvoiceMate.Domain\InvoiceMate.Domain.csproj" />
  </ItemGroup>

</Project>
